export const LOAD_API_DATA = 'LOAD_API_DATA'

export const CREATING_USER = 'CREATING_USER'
export const CREATED_USER = 'CREATED_USER'
export const FAILED_SIGNUP = 'FAILED_SIGNUP'

export const AUTHENTICATING_USER = 'AUTHENTICATING_USER'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const FAILED_LOGIN = 'FAILED_LOGIN'
export const UNMOUNT_USER_FORM = 'UNMOUNT_USER_FORM'

export const UPDATING_USER = 'UPDATING_USER'
export const UPDATED_USER = 'UPDATED_USER'
export const FAILED_UPDATE = 'FAILED_UPDATE'

export const MAKING_RESERVATION = 'MAKING_RESERVATION'
export const MAKE_RESERVATION = 'MAKE_RESERVATION'
export const CANCEL_RESERVATION = 'CANCEL_RESERVATION'
export const CANCELLING_RESERVATION = 'CANCELLING_RESERVATION'

export const RENDER_RESERVED_TOUR = 'RENDER_RESERVED_TOUR'

export const CREATING_TOUR = 'CREATING_TOUR'
export const CREATE_TOUR = 'CREATE_TOUR'
export const FAILED_CREATE_TOUR = 'FAILED_CREATE_TOUR'
export const UNMOUNT_TOUR = 'UNMOUNT_TOUR'
